### ISSUE TITLE
Adding silder to efficeintly navigate the flascards cards 

### ISSUE THREAD

**Issue by AkhilChawla** [WolfByteCollective/FlashCards#1]
Currently, the flashcard app displays all user-created cards vertically, which can lead to a cluttered view when many cards are added. To improve usability and layout, I propose implementing a horizontal slider for card navigation.

**Proposed Solution**

- Display all cards in one horizontal row.
- Add left and right arrow buttons to scroll through the cards.
- Include a scroll bar for additional control over navigation.
- Ensure the slider is responsive

This enhancement will create a cleaner, more efficient UI, making it easier for users to browse through their cards without overwhelming the screen space.

**Acceptance Criteria**

- Cards are arranged in a horizontal row.
- Arrow buttons function correctly to scroll left and right.
- A scroll bar provides smooth and intuitive navigation.
- Layout remains responsive on various devices.

**Comment by AkhilChawla** [comment]
I think we will need to create this card population row as a separate component so that we can utilize it in your tasks as well. @PriyaGandhi311 @sdalal11

**Comment by PriyaGandhi311** [comment]
We can look into this during our next review meeting.

**Comment by AkhilChawla** [comment]
Issue resolved with the following PR - https://github.com/WolfByteCollective/FlashCards/pull/2
